---
# Location where configuration files will be stored.
config_dir: '~'

restic_version: '0.13.1'
cameras: "basement driveway garden irongate"

cron_clean_hour: 4
cron_clean_minute: 0

cron_backup_hour: 2
cron_backup_minute: 0

b2_account_id: ''
b2_key: ''
# b2:b2_bucket:b2_dir
b2_bucket: ''
b2_dir: ''
b2_pass: ''

keep_within: '1m' # 1 month
remove_after_days: 4
